# Please restart the server process if you change this file.

# Theme settings
remote_theme                  : "mmistakes/minimal-mistakes@4.19.1"
minimal_mistakes_skin         : "air" # "default", air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
# Any variables created here can be accessed in templates
# (but not front matter) via {{site.title}}, {{site.email}}, and so on.
locale                        : "en-US"

title                         : "Old books and musty smells"
title_separator               : "|"
subtitle                      : "book reviews for mortals"
name                          : &name "Iha Bansal"
description                   : &description "heartfelt book reviews written by a mortal for my fellow mortals"

url                           : https://iha92.github.io
baseurl                       : ""
repository                    : "iha92/iha92.github.io"

# Fallback teaser image used in 'Related Posts', if article does not have defined teaser image
# teaser                        : /assets/images/teaser-500x300.png

# Logo image to be inserted before site title in website masthead
# logo                          : /assets/images/logo-88x88.png

# When shared across the internet, this image is used if article does not have header.image assigned.
# Minimum 120 x 120px and less than 1 MB
# og_image                      : /assets/images/logo-120x120.png

words_per_minute              : 200

social:
  type                        : # Person or Organization (defaults to Person)
  name                        : *name
  links: # An array of links to social media profiles
    - "https://www.facebook.com/iha"

# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Freeman_%26_Colley-Lee_crop.jpg/249px-Freeman_%26_Colley-Lee_crop.jpg"
  bio              : "yaha bio daalni hai"
  # location         : "Mumbai, India"
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: &instagram "https://instagram.com/iha"

# Site Footer
footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: *instagram

# Reading Files
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: " \n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      # related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:title
paginate: 5
paginate_path: /page:num/
timezone: Asia/Kolkata # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  # - jekyll-remote-theme

# mimic GitHub Pages with --safe
whitelist: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  # - jekyll-remote-theme

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /

# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/

# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

compress_html:
  clippings: all
  ignore:
    envs: development
